runtime: nodejs

env: flex

manual_scaling:
  instances: 2
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

env_variables:
  SQL_USER: raul
  SQL_PASSWORD: raul
  SQL_DATABASE: gestor-siniestros:us-central1:gs-prod
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: test-prod
# [END gae_flex_mysql_env]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: test-prod
